[package]
name = "mhxg-crawler"
version = "0.1.0"
authors = ["Jonir Rings <peterpuyi@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
